# Generated by Django 3.2.12 on 2024-01-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocjena',
            name='polaznik',
        ),
        migrations.AddField(
            model_name='ocjena',
            name='polaznik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.polaznik'),
        ),
        migrations.RemoveField(
            model_name='ocjena',
            name='tecaj',
        ),
        migrations.AddField(
            model_name='ocjena',
            name='tecaj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tecaj'),
        ),
    ]
